server:
  port: 8001
spring:
  application:
    name: clother-client
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/clothes?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 399399

eureka:
  client:
    service-url:
      -defaultZone: http://localhost:8000/eureka

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
