server:
  port: 8001
spring:
  application:
    name: clother-client
  datasource:
    url: jdbc:mysql://120.78.166.226:3306/clothes?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
#    url: jdbc:mysql://127.0.0.1:3306/clothes?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: 399399
    password: 123456
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 100
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
    tomcat:
      validation-query: SELECT 1
      test-on-borrow: true
      test-while-idle: true
      test-on-return: false
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false


eureka:
  client:
    service-url:
      -defaultZone: http://localhost:8000/eureka

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
