server:
  port: 8001
spring:
  application:
    name: clother-client
  datasource:
    url: jdbc:mysql://120.78.166.226:3306/clothes?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
#    url: jdbc:mysql://127.0.0.1:3306/clothes?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: 399399
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat,wall,log4j
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 20
      max-wait-millis: 60000
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false


eureka:
  client:
    service-url:
      -defaultZone: http://localhost:8000/eureka

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
